language: node_js
node_js:
  - node
dist: trusty
sudo: false

branches:
  only:
  - dev

cache:
  directories:
    - node_modules

script:
  - yarn build --production

# after_success:
#   - bash ./scripts/deploy-to-gh-pages.sh

notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always

